// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermitToWorkRepf.Data;

namespace PermitToWorkEpf.Migrations
{
    [DbContext(typeof(RepfDbContext))]
    [Migration("20200326194333_REPF")]
    partial class REPF
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("PermitToWorkRepf.Models.Machine", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.HasKey("name");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.SignIn", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("StudentId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentId1");

                    b.ToTable("SignIns");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.Student", b =>
                {
                    b.Property<ulong>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Graduation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.SignIn", b =>
                {
                    b.HasOne("PermitToWorkRepf.Models.Student", "Student")
                        .WithMany("SignIns")
                        .HasForeignKey("StudentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
