// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermitToWorkRepf.Data;

namespace tmp.Migrations
{
    [DbContext(typeof(RepfDbContext))]
    partial class RepfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("PermitToWorkRepf.Models.Machine", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.SignIn", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("MachineName");

                    b.HasIndex("StudentId");

                    b.ToTable("SignIns");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.Student", b =>
                {
                    b.Property<ulong>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Graduation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PermitToWorkRepf.Models.SignIn", b =>
                {
                    b.HasOne("PermitToWorkRepf.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineName");

                    b.HasOne("PermitToWorkRepf.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");
                });
#pragma warning restore 612, 618
        }
    }
}
